baseURL = "https://adachic.github.io/"
languageCode = "ja"
title = "東のレガリア"
theme = "vienna"
canonifyurls = true
publishdir = "public"
[params]
  subtitle = "必要なことをやっていく"
  github = "adachic"
  twitter = "adachi_c"
  ga_api_key = "UA-53227080-3"
