baseURL = "https://adachic.github.io/"
languageCode = "ja"
title = "東のレガリア"
theme = "vienna"
canonifyurls = true
googleAnalytics = "UA-53227080-3"
[params]
  Subtitle = "必要なことをやっていく"
  AuthorName = "Akinori ADACHI"
  GitHubUser = "adachic"
  SidebarRecentLimit = 5
